In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import os
from PIL import Image
import cv2
import seaborn as sns

In [8]:
img_dir = '/content/drive/MyDrive/딥러닝/이미지/'
categoris = os.listdir(img_dir)
nb_categoris = len(categoris)
image_total=0
count_list=[]

def folder_image_count(path):
    image_count = os.listdir(path)
    return len(image_count)

for i in range(nb_categoris):
    count=folder_image_count(img_dir+categoris[i])
    print("{0} : {1}개".format(categoris[i],count))
    image_total+=count
    count_list.append(count)
print("클래스의 개수는 {0}개 입니다".format(nb_categoris))
print("전체 데이터 개수는 {0}개 입니다.".format(image_total))

BMW : 611개
아우디 : 0개
클래스의 개수는 2개 입니다
전체 데이터 개수는 611개 입니다.

In [10]:
import math
percent_list=[]
for i in range(nb_categoris):
  percent=count_list[i] / image_total * 100
  percent=round(percent,3)
  percent_list.append(percent)
dataframe=pd.DataFrame({"Category":categoris,
                      "Count": count_list,
                      "Percent": percent_list} )
dataframe.T

              0       1
Category    BMW  아우디
Count       611       0
Percent   100.0     0.0

In [12]:
 import glob
 #print(nb_categoris)
 img_name_list=[] # 파일명 리스트
 channel_list=[]  # 영상 채널 리스트
 ext_list=[] # 확장자 리스트
 width_list=[] # 영상 데이터 가로 길이
 height_list=[] # 영상 데이터 세로 길이
 cat_list=[] # 클래스
 path_list=[] # 이미지 경로
 for i in range(nb_categoris):
   a=glob.glob(img_dir+categoris[i]+'/*')
   for j in range(len(a)):
     cat_img_name= a[j].split('/')[-2:]
     img_name=cat_img_name[-1]
     cat=cat_img_name[0]
     ext=img_name.split('.')[-1]
     #print(cat)
     #print(img_name)
     #print(ext)
     img = cv2.imread(a[j], cv2.IMREAD_UNCHANGED) #cv2.IMREAD_UNCHANGED 해당 옵션이 있어야 채널값이 4인 데이터 분별 가능 
     if img.ndim ==2: # 흑백 이미지의 경우 채널값이 없는 2차원 배열이므로 조건문처리
       w, h = img.shape
       c=1
     else:
       w, h, c = img.shape
     cat_list.append(cat)
     img_name_list.append(img_name)
     ext_list.append(ext)
     width_list.append(w)
     height_list.append(h)
     channel_list.append(c)
     path_list.append(a[j])

In [13]:
 img_info=pd.DataFrame({"IMG_ID":img_name_list,
                        "Category": cat_list,
                       "Extension": ext_list,
                       "Width": width_list,
                       "Height": height_list,
                       "Channel": channel_list,
                        "Path": path_list} )
 img_info

,IMG_ID,Category,Extension,Width,Height,Channel,Path
0,한BMW351.jpg,BMW,jpg,181,278,3,/content/drive/MyDrive/딥러닝/이미지/BMW/한BMW...
1,한BMW340.jpg,BMW,jpg,183,275,3,/content/drive/MyDrive/딥러닝/이미지/BMW/한BMW...
2,한BMW32.jpg,BMW,jpg,225,225,3,/content/drive/MyDrive/딥러닝/이미지/BMW/한BMW...
3,한BMW35.jpg,BMW,jpg,194,259,3,/content/drive/MyDrive/딥러닝/이미지/BMW/한BMW...
4,한BMW328.jpg,BMW,jpg,194,259,3,/content/drive/MyDrive/딥러닝/이미지/BMW/한BMW...
...,...,...,...,...,...,...,...
606,한BMW88.jpg,BMW,jpg,183,275,3,/content/drive/MyDrive/딥러닝/이미지/BMW/한BMW...
607,한BMW83.jpg,BMW,jpg,183,275,3,/content/drive/MyDrive/딥러닝/이미지/BMW/한BMW...
608,한BMW80.jpg,BMW,jpg,183,275,3,/content/drive/MyDrive/딥러닝/이미지/BMW/한BMW...
609,한BMW76.jpg,BMW,jpg,183,275,3,/content/drive/MyDrive/딥러닝/이미지/BMW/한BMW...
610,한BMW77.jpg,BMW,jpg,168,300,3,/content/drive/MyDrive/딥러닝/이미지/BMW/한BMW...

In [18]:
img_info[img_info.Channel==4]

,IMG_ID,Category,Extension,Width,Height,Channel,Path
167,BMW1.jpg,BMW,jpg,192,320,4,/content/drive/MyDrive/딥러닝/이미지/BMW/BMW1.jpg